### ISSUE TITLE
Error when scss file is empty or only has comments

### ISSUE THREAD

**Issue by Mqxx** [hironichu/denosass#17]
Hey, I'm currently writing a sass plugin for esbuild, and I noticed that the transpiler doesn't work with empty files or if the files only contain comments.

SCSS file content (or just empty):
```scss
//
```

The plugin looks like this:
```ts
import * as esbuild from "https://deno.land/x/esbuild@v0.19.11/mod.js";
import sass from "https://deno.land/x/denosass@1.0.6/mod.ts"

const sassPlugin: esbuild.Plugin = {
    name: "esbuild-plugin-sass",
    setup: (build) => {
        build.onLoad(
            { filter: /\.scss$/g },
            async (args) => {
                const file = await Deno.readTextFile(args.path)
                
                
                const css = sass(
                    file,
                    { style: build.initialOptions.minify ? 'compressed' : 'expanded' }
                ).to_string()

                return {
                    contents: css.toString() || '',
                    loader: 'css'
                }
            }
        )
    }
}

await esbuild.build({
    allowOverwrite: true,
    logLevel: 'info',
    minify: true,
    outdir: './dist',
    entryNames: '[dir]/bundle.min',
    entryPoints: [
        './src/**/index.scss'
    ],
    plugins: [
        sassPlugin
    ]
})
```

It does work fine unless the file is empty or only contains comments. I get this error:
```
1 error
error: Uncaught (in promise) Error: Build failed with 1 error:
error: The specified path name is invalid. (os error 161): readdir '//' for path "\"
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.11/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.11/mod.js:1034:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.11/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.11/mod.js:1032:7)
    at https://deno.land/x/esbuild@v0.19.11/mod.js:1061:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.11/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.11/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.11/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.11/mod.js:1933:11
    at eventLoopTick (ext:core/01_core.js:178:11)
```

**Comment by Mqxx** [comment]
I am also not sure whether the error comes from ESBuild or from DenoSass...

**Comment by Mqxx** [comment]
Okay it comes fom DenoSass. Looks like DenoSass is trying for some reason to use the file content as a path...

```
Error: The syntax for the file name, directory name or data carrier designation is incorrect. (os error 123): readdir '
'
    at Object.readDirSync (ext:deno_fs/30_fs.js:149:14)
    at walkSync (https://deno.land/std@0.162.0/fs/walk.ts:161:20)
    at walkSync.next (<anonymous>)
    at Sass.#processDir (https://deno.land/x/denosass@1.0.6/src/mod.ts:338:13)
    at Sass.#checkType (https://deno.land/x/denosass@1.0.6/src/mod.ts:300:38)
    at new Sass (https://deno.land/x/denosass@1.0.6/src/mod.ts:99:27)
    at sass (https://deno.land/x/denosass@1.0.6/src/mod.ts:388:10)
    at file:///D:/github/JavaScriptPlayground/Template/build.config.ts:16:27
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async requestCallbacks.on-load (https://deno.land/x/esbuild@v0.19.11/mod.js:1410:22) {
  root: "\n",
  message: "The syntax for the file name, directory name or data carrier designation is incorrect. (os erro"... 32 more characters,
  cause: undefined
}
```

**Comment by Mqxx** [comment]
Found a solution...

```ts
const sassPlugin: esbuild.Plugin = {
    name: "esbuild-plugin-sass",
    setup: (build) => {
        build.onLoad(
            { filter: /\.scss$/ },
            async (args) => {
                const file = await Deno.readTextFile(args.path)
                
                const css = sass(
                    file,
                    { style: build.initialOptions.minify ? 'compressed' : 'expanded' }
                ).to_string()

                if (css instanceof Map) {
                    return {
                        contents: css.get('index'),
                        loader: 'css'
                    }
                } else if (typeof css === 'string') {
                    return {
                        contents: css,
                        loader: 'css'
                    }
                } else {
                    return {
                        contents: '',
                        loader: 'css'
                    }
                }
            }
        )
    }
}
```

**Comment by Mqxx** [comment]
Okay after some testing I can confirm that the error is still there... Error on:

- File only includes single line comment (//) not on multiline (/**/)
- File only includes single linebreak without any other content.

**Comment by hironichu** [comment]
I appreciate your help and support, however like i replied before i really don't have time to continue to maintain this.

I have ideas / plans.. but nothing until i finish my academic year.

Also, i might archive this repo to make sure its known that it wont be supported (for now?)

**Comment by Mqxx** [comment]
Thank you for your answer. I'd like to help more but unfortunately I'm not really familiar with WebAssembly at the moment and I also don't have much time. I've only worked with Deno FFI so far (which is similar, but not the same...).
